export async function request(path, body, options = {}) { const response = await fetch(path, { method: options.method || 'POST', headers: { 'content-type': 'application/json', ...(options.headers || {}) }, credentials: 'same-origin', body: body === undefined ? undefined : JSON.stringify(body) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'No se pudo completar la operación.'); return data; }
const byId = id => document.getElementById(id); const write = (id, message, ok = false) => { const node = byId(id); node.textContent = message; node.className = `notice${ok ? ' success' : ''}`; };
async function loadAccount() { try { const { account } = await fetch('/api/account', { credentials: 'same-origin' }).then(async response => { if (!response.ok) throw Error(); return response.json(); }); if (!account) throw Error(); byId('auth-view').classList.add('hidden'); byId('account-view').classList.remove('hidden'); byId('account-name').textContent = `${account.first_name} ${account.last_name}`; byId('account-contact').textContent = `${account.email} · ${account.phone}`; const active = account.status === 'active' && new Date(account.end_date) >= new Date(); byId('membership-summary').innerHTML = account.plan ? `<p><b>Plan:</b> ${account.plan === 'basic' ? 'Preparación Básica' : 'Preparación Completa'}<br><b>Estado:</b> ${active ? 'Activo' : account.status}<br><b>Activación:</b> ${account.start_date ? new Date(account.start_date).toLocaleDateString('es-PE') : 'Pendiente'}<br><b>Vencimiento:</b> ${account.end_date ? new Date(account.end_date).toLocaleDateString('es-PE') : 'Pendiente'}</p>` : '<p>Aún no tienes una membresía. Elige un plan para continuar.</p>'; byId('continue-study').textContent = active ? 'CONTINUAR ESTUDIANDO' : 'RENOVAR MEMBRESÍA'; } catch { byId('logout')?.classList.add('hidden'); } }
byId('login-form')?.addEventListener('submit', async event => { event.preventDefault(); try { await request('/api/auth/login', Object.fromEntries(new FormData(event.currentTarget))); location.reload(); } catch (cause) { write('login-notice', cause.message); } });
byId('register-form')?.addEventListener('submit', async event => { event.preventDefault(); try { await request('/api/auth/register', Object.fromEntries(new FormData(event.currentTarget))); location.reload(); } catch (cause) { write('register-notice', cause.message); } });
byId('show-recovery')?.addEventListener('click', event => { event.preventDefault(); byId('recovery-card').classList.remove('hidden'); });
byId('recovery-form')?.addEventListener('submit', async event => { event.preventDefault(); try { const data = await request('/api/auth/forgot-password', Object.fromEntries(new FormData(event.currentTarget))); write('recovery-notice', data.message, true); } catch (cause) { write('recovery-notice', cause.message); } });
byId('logout')?.addEventListener('click', async () => { await request('/api/auth/logout', {}); location.reload(); });
document.querySelectorAll('[data-plan]').forEach(button => button.addEventListener('click', async () => { try { write('payment-notice', 'Preparando pago de prueba…', true); const key = crypto.randomUUID().replaceAll('-', ''); const data = await request('/api/payments/create', { plan: button.dataset.plan }, { headers: { 'idempotency-key': key } }); if (data.checkoutUrl) location.assign(data.checkoutUrl); else if (data.mockApproval) { const confirm = window.confirm('Modo local: simular aprobación de este pago sin usar dinero real?'); if (!confirm) return write('payment-notice', 'La orden local quedó pendiente.'); await request('/api/payments/mock-approve', { paymentId: data.paymentId }); write('payment-notice', 'Pago local simulado y membresía activada.', true); await loadAccount(); } else write('payment-notice', 'Ya existe una orden pendiente para esta operación.'); } catch (cause) { write('payment-notice', cause.message); } }));
async function reconcileReturn() { const params = new URLSearchParams(location.search); const paymentId = params.get('payment_id') || params.get('collection_id'); if (!paymentId || params.get('collection_status') !== 'approved') return; try { await request('/api/payments/reconcile', { paymentId }); history.replaceState({}, '', 'mi-cuenta.html'); } catch {} }
await reconcileReturn();
try { await request('/api/payments/reconcile', {}); } catch {}
loadAccount();
