import { api, assertSameOrigin, db, error, json, query, readJson, requireMethod, requireUser } from '../_lib.js';
export default api(async request => {
  requireMethod(request, 'POST'); assertSameOrigin(request); const user = requireUser(request); const { kind, answers } = await readJson(request);
  if (!['diagnostic', 'simulator'].includes(kind) || !Array.isArray(answers) || answers.length < 1 || answers.length > 20) return error('Respuestas inválidas.', 422);
  if (kind === 'simulator') { const membership = await query("SELECT 1 FROM subscriptions WHERE user_id=$1 AND status='active' AND end_date>=NOW()", [user.sub]); if (!membership.rowCount) return error('Necesitas una membresía activa para enviar un simulacro.', 403); }
  const ids = answers.map(answer => answer.questionId); if (new Set(ids).size !== ids.length || answers.some(answer => !Number.isInteger(answer.selectedOption) || answer.selectedOption < 0 || answer.selectedOption > 3)) return error('Respuestas inválidas.', 422);
  const rows = await query('SELECT id,category,correct_option,explanation FROM questions WHERE id=ANY($1::uuid[]) AND is_active=true', [ids]); if (rows.rowCount !== ids.length) return error('Una o más preguntas no son válidas.', 422);
  const answersById = new Map(answers.map(answer => [answer.questionId, answer.selectedOption])); const grading = rows.rows.map(question => ({ ...question, selectedOption: answersById.get(question.id), correct: answersById.get(question.id) === question.correct_option }));
  const categoryScores = Object.fromEntries(['mathematics', 'reading'].map(category => { const selected = grading.filter(item => item.category === category); return [category, { correct: selected.filter(item => item.correct).length, total: selected.length }]; }));
  const correct = grading.filter(item => item.correct).length, score = Number(((correct / grading.length) * 100).toFixed(2)); const client = await db().connect();
  try { await client.query('BEGIN'); const attempt = (await client.query('INSERT INTO assessment_attempts (user_id,kind,total_questions,correct_answers,score,category_scores) VALUES ($1,$2,$3,$4,$5,$6) RETURNING id', [user.sub, kind, grading.length, correct, score, JSON.stringify(categoryScores)])).rows[0]; for (const answer of grading) await client.query('INSERT INTO assessment_answers (attempt_id,question_id,selected_option,is_correct) VALUES ($1,$2,$3,$4)', [attempt.id, answer.id, answer.selectedOption, answer.correct]); await client.query('COMMIT'); return json({ attemptId: attempt.id, score, correct, total: grading.length, categoryScores, feedback: grading.map(item => ({ questionId: item.id, correct: item.correct, correctOption: item.correct_option, explanation: item.explanation })) }); } catch (cause) { await client.query('ROLLBACK'); throw cause; } finally { client.release(); }
});
